### ISSUE TITLE
Just a suggestion of app name

### ISSUE THREAD

**Issue by woeijiunn88** [ELynx/pokemon-go-xposed-mitm#1]
Change the app name to PokéMitm could be better look.
Actually i don't know Mitm meaning.

**Comment by krokofant** [comment]
_MITM_ stands for Man In The Middle. It's in the name because it describes the core purpose of this module, to stealthy intercept and/or modify the data send to and from the app.

I think the name nicely captures what it is and how it's implemented. I'd assume developers using this won't be concerned about the name. _PokéMitm_ sounds more like a branded product aimed for the masses than a software project of this nature. 🍰

**Comment by woeijiunn88** [comment]
Ok, i see.
