### ISSUE TITLE
Ban possibility

### ISSUE THREAD

**Issue by cire27rn** [ELynx/pokemon-go-xposed-mitm#12]
Is this app harder to detect from niantic? One cause of ban is data scrape and if maybe this can be detected

**Comment by ELynx** [comment]
@cire27rn This application do not modify data sent to Niantic servers, and do not do additional requests. It only examines data being sent, and modify data received back.
Thus this don't generate additional traffic.
If Niantic ever work on detection of XPosed, then this may become an issus. Now I had not heard/read about bans for this or similar apps.

Long-term plan for this module is to become full-scripted MitM module, then more dangerous stuff can be made. But worry not - any dangerous action will have from 2km to 10km of do-not-cross duct tape and safety belts. Beside regular warnings.

**Comment by labmonkey** [comment]
@ELynx Actually I was wondering about this myself when I found this app. I think that readme could be more detailed about this (even include your answer). The current readme section "What it can do now" could clarify 2 most important things for newcomers. First it's that it doesn't use API at all like everything else which could be surprising for some that there is other way. Second thing is that you wrote that it "Intercept packages going from server to client, too." This leaves people thinking that it is changing data going to server and is risky to use because could be detected. Maybe be more specific and write why data going to server is also changed and what for?
