### ISSUE TITLE
PoGo randomly crashed after enabling module

### ISSUE THREAD

**Issue by alexkruegger** [ELynx/pokemon-go-xposed-mitm#9]
Xiaomi Redmi note 2, AOSP 5.0.2. Tested on 0.33 and 0.35. PoGo randomly crashed without any notice.
In the module IV check is off, Lure time is on.

Just for u information )

**Comment by ELynx** [comment]
I had reports of Xiaomi something something not doing anything with any settings, may be this is related too.
Does this chinese thing even have XPosed, "official"? All I saw was a port, may be this is the case.
I also heard that Xiaomi have some sort of additional secutiry settings for apps, can it be that some permissions are denied for PoGo or module?

This MAY be fixed with either #7 or #5.

**Comment by ELynx** [comment]
Please try beta release 1.3, see if anything changes. It has networking improved, and UI rework.

**Comment by alexkruegger** [comment]
Well, Thank you! I'll try it tomorrow and leave feedback.

**Comment by ELynx** [comment]
@alexkruegger Any news?

**Comment by riththerift** [comment]
Hi,

V1.3.2 crashes as soon as it is opened. It occurred after enabling the module and selecting what I wanted to turn on.

**Comment by ELynx** [comment]
@xstahsie Please give app storage permissions, and try again.

**Comment by alexkruegger** [comment]
@ELynx Well, 1.3.2 is stable (at least until now), run PoGO for an hours without crashes. Thank you! )
Will test more and report in any case.

**Comment by ELynx** [comment]
@alexkruegger Great, will keep this open then for some time.
Probably it crashed for same reason as #7, bad connection.

**Comment by riththerift** [comment]
After enabling storage permission, the app no longer crashes.
